Repository TreinaDev/pague-aluguel, pull requests merged in 2024-07, with the labels that each got.

#30 Taxa de Áreas Comuns
  .gitignore
  Gemfile
  Gemfile.lock
  app/controllers/common_areas_controller.rb
  app/models/common_area.rb
  app/models/common_area_fee_history.rb
  app/models/condo.rb
  app/views/common_areas/edit.html.erb
  app/views/common_areas/index.html.erb
  app/views/common_areas/show.html.erb
  app/views/condos/show.html.erb
  config/initializers/devise.rb
  config/locales/common_area_fee.pt-BR.yml
  config/locales/devise.pt-BR.yml
  config/locales/rails.pt-BR.yml
  config/routes.rb
  db/migrate/20240625191237_create_common_areas.rb
  db/migrate/20240626203803_remove_fee_from_common_areas.rb
  db/migrate/20240626203935_add_fee_to_common_areas.rb
  db/migrate/20240627214305_create_common_area_fee_histories.rb
  db/migrate/20240628194953_rename_fee_from_common_areas.rb
  db/migrate/20240628202418_rename_fee_from_common_area_fee_histories.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/common_area_fee_histories.rb
  spec/factories/common_areas.rb
  spec/models/admin_spec.rb
  spec/models/common_area_fee_history_spec.rb
  spec/models/common_area_spec.rb
  spec/models/custom_fee_spec.rb
  spec/models/property_owner_spec.rb
  spec/models/unit_spec.rb
  spec/models/unit_type_spec.rb
  spec/requests/common_area_fee/update_common_area_fee_spec.rb
  spec/system/admin/admin_registers_another_admin_spec.rb
  spec/system/admin_access_condo_managing_page_spec.rb
  spec/system/base_fees/admin_creates_new_base_fee_spec.rb
  spec/system/base_fees/admin_sees_base_fee_details_spec.rb
  spec/system/common_areas_fees/admin_register_common_area_fee_spec.rb
  spec/system/common_areas_fees/admin_view_common_area_spec.rb
  spec/system/common_areas_fees/admin_view_common_areas_list_spec.rb
  spec/system/shared_fee/admin_access_shared_fee_list_spec.rb
Labels: enhancement

#51 Registro de Proprietário
  app/controllers/property_owners/registrations_controller.rb
  app/controllers/property_owners/sessions_controller.rb
  app/models/property_owner.rb
  app/views/layouts/_navbar.html.erb
  app/views/owner_cpf_validations/new.html.erb
  app/views/property_owners/confirmations/new.html.erb
  app/views/property_owners/mailer/confirmation_instructions.html.erb
  app/views/property_owners/mailer/email_changed.html.erb
  app/views/property_owners/mailer/password_change.html.erb
  app/views/property_owners/mailer/reset_password_instructions.html.erb
  app/views/property_owners/mailer/unlock_instructions.html.erb
  app/views/property_owners/passwords/edit.html.erb
  app/views/property_owners/passwords/new.html.erb
  app/views/property_owners/registrations/edit.html.erb
  app/views/property_owners/registrations/new.html.erb
  app/views/property_owners/sessions/new.html.erb
  app/views/property_owners/shared/_error_messages.html.erb
  app/views/property_owners/shared/_links.html.erb
  app/views/property_owners/unlocks/new.html.erb
  config/locales/devise.pt-BR.yml
  config/locales/pt-BR.yml
  config/locales/rails.pt-BR.yml
  config/routes.rb
  db/migrate/20240703183614_add_document_id_to_property_owners.rb
  db/migrate/20240704185220_rename_document_id_in_property_owners.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/property_owners.rb
  spec/models/property_owner_spec.rb
  spec/requests/admins/user_registers_admin_spec.rb
  spec/system/admins/admin_edits_account_spec.rb
  spec/system/admins/admin_registers_another_admin_spec.rb
  spec/system/admins/admin_signs_in_spec.rb
  spec/system/property_owners/property_owners_sign_in_spec.rb
  spec/system/property_owners/user_tries_to_sign_up_as_property_owners_spec.rb
Labels: enhancement

#52 Cancela conta compartilhada
  app/controllers/shared_fees_controller.rb
  app/models/shared_fee.rb
  app/models/shared_fee_fraction.rb
  app/views/condos/show.html.erb
  app/views/shared_fees/index.html.erb
  app/views/shared_fees/new.html.erb
  app/views/shared_fees/show.html.erb
  config/locales/rails.pt-BR.yml
  config/locales/shared_fee.pt-BR.yml
  config/routes.rb
  db/migrate/20240704142530_add_status_to_shared_fees.rb
  db/schema.rb
  spec/requests/shared_fees/shared_fees_spec.rb
  spec/system/condos/admin_access_condo_managing_page_spec.rb
  spec/system/shared_fees/admin_access_shared_fee_list_spec.rb
  spec/system/shared_fees/admin_cancels_shared_fee_spec.rb
  spec/system/shared_fees/admin_creates_shared_fee_spec.rb
Labels: enhancement

#57 Navegação para Conta Compartilhada
  app/controllers/shared_fees_controller.rb
  app/views/condos/show.html.erb
  app/views/home/index.html.erb
  app/views/shared_fees/index.html.erb
  app/views/shared_fees/new.html.erb
  app/views/shared_fees/show.html.erb
  config/routes.rb
  spec/requests/shared_fees/shared_fees_spec.rb
  spec/system/shared_fees/admin_access_shared_fee_list_spec.rb
  spec/system/shared_fees/admin_cancels_shared_fee_spec.rb
  spec/system/shared_fees/admin_creates_shared_fee_spec.rb
Labels: enhancement

#55 Cadastro de Taxas Limitadas
  app/assets/stylesheets/modal.scss
  app/controllers/base_fees_controller.rb
  app/javascript/controllers/index.js
  app/javascript/controllers/toggle_installments_field_controller.js
  app/models/base_fee.rb
  app/models/custom_fee.rb
  app/models/value.rb
  app/views/base_fees/new.html.erb
  app/views/base_fees/show.html.erb
  config/locales/base_fees.pt-BR.yml
  config/locales/rails.pt-BR.yml
  db/migrate/20240705144023_rename_fixed_from_base_fees.rb
  db/migrate/20240705144327_change_limited_from_base_fees.rb
  db/migrate/20240705172435_add_installments_to_base_fee.rb
  db/migrate/20240705182946_drop_custom_fees.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/base_fees.rb
  spec/factories/custom_fees.rb
  spec/models/base_fee_spec.rb
  spec/models/custom_fee_spec.rb
  spec/system/base_fees/admin_creates_new_base_fee_spec.rb
  spec/system/base_fees/admin_sees_base_fee_details_spec.rb
  spec/system/base_fees/admin_sees_base_fee_list_spec.rb
Labels: enhancement

#53 Listagem, Cobrança e Histórico de Áreas Comuns
  .gitignore
  app/controllers/common_area_fees_controller.rb
  app/controllers/common_areas_controller.rb
  app/controllers/condos_controller.rb
  app/models/admin.rb
  app/models/common_area.rb
  app/models/common_area_fee.rb
  app/models/common_area_fee_history.rb
  app/views/common_area_fees/new.html.erb
  app/views/common_areas/_common_area_fee_histories.html.erb
  app/views/common_areas/edit.html.erb
  app/views/common_areas/show.html.erb
  app/views/condos/_common_areas_section.html.erb
  app/views/property_owners/sessions/new.html.erb
  app/views/shared_fees/show.html.erb
  config/locales/common_area_fee.pt-BR.yml
  config/routes.rb
  db/migrate/20240704181711_drop_common_areas.rb
  db/migrate/20240704184254_drop_table_common_area_fee_histories.rb
  db/migrate/20240705183522_create_common_area_fees.rb
  db/migrate/20240705195817_add_common_area_id_to_common_area_fees.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/common_area_fee_histories.rb
  spec/factories/common_area_fees.rb
  spec/models/common_area_fee_history_spec.rb
  spec/models/common_area_fee_spec.rb
  spec/models/common_area_spec.rb
  spec/requests/common_area_fee/update_common_area_fee_spec.rb
  spec/support/json/common_areas.json
  spec/system/base_fees/admin_creates_new_base_fee_spec.rb
  spec/system/base_fees/admin_sees_base_fee_details_spec.rb
  spec/system/base_fees/admin_sees_base_fee_list_spec.rb
  spec/system/common_areas_fees/admin_register_common_area_fee_spec.rb
  spec/system/common_areas_fees/admin_sees_common_area_fees_history_spec.rb
  spec/system/common_areas_fees/admin_view_common_area_spec.rb
  spec/system/common_areas_fees/admin_view_common_areas_list_spec.rb
  spec/system/condos/admin_access_condo_managing_page_spec.rb
  spec/system/shared_fees/admin_access_shared_fee_list_spec.rb
  spec/system/shared_fees/admin_cancels_shared_fee_spec.rb
  spec/system/shared_fees/admin_creates_shared_fee_spec.rb
Labels: API

#65 Geração Automática de Fatura
  Gemfile
  Gemfile.lock
  app/jobs/generate_monthly_bill_job.rb
  app/models/bill.rb
  app/models/bill_calculator.rb
  app/models/unit.rb
  config/schedule.rb
  db/migrate/20240710152941_create_bills.rb
  db/schema.rb
  lib/tasks/batch.rake
  spec/factories/bills.rb
  spec/jobs/generate_monthly_bill_job_spec.rb
  spec/models/bill_calculator_spec.rb
  spec/models/bill_spec.rb
  spec/tasks/generate_bill_spec.rb
Labels: Jobs

#71 Adiciona Preview de Contas e Padroniza Modais
  app/controllers/base_fees_controller.rb
  app/controllers/condos_controller.rb
  app/controllers/shared_fees_controller.rb
  app/views/admins/registrations/edit.html.erb
  app/views/admins/registrations/new.html.erb
  app/views/admins/sessions/new.html.erb
  app/views/base_fees/index.html.erb
  app/views/base_fees/show.html.erb
  app/views/common_area_fees/new.html.erb
  app/views/common_areas/show.html.erb
  app/views/condos/_base_fees_section.html.erb
  app/views/condos/_shared_fees_section.html.erb
  app/views/condos/show.html.erb
  app/views/home/choose_profile.html.erb
  app/views/property_owners/registrations/new.html.erb
  app/views/property_owners/sessions/new.html.erb
  app/views/shared_fees/show.html.erb
  spec/requests/base_fees/base_fees_spec.rb
  spec/requests/shared_fees/shared_fees_spec.rb
  spec/system/base_fees/admin_creates_new_base_fee_spec.rb
  spec/system/base_fees/admin_sees_base_fee_list_spec.rb
  spec/system/shared_fees/admin_access_shared_fee_list_spec.rb
  spec/system/shared_fees/admin_creates_shared_fee_spec.rb
Labels: enhancement, feedback

#64 Lançamento de Cobranças Avulsas (Administrador)
  app/controllers/single_charges_controller.rb
  app/javascript/controllers/index.js
  app/javascript/controllers/toggle_common_area_field_controller.js
  app/models/single_charge.rb
  app/models/unit.rb
  app/views/condos/_payment_slip_section.html.erb
  app/views/condos/_single_charge_section.html.erb
  app/views/condos/show.html.erb
  app/views/single_charges/index.html.erb
  app/views/single_charges/new.html.erb
  app/views/single_charges/show.html.erb
  config/locales/condo.pt-BR.yml
  config/locales/single_charge.pt-BR.yml
  config/routes.rb
  db/migrate/20240710134714_create_single_charges.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/single_charges.rb
  spec/models/single_charge_spec.rb
  spec/models/unit_spec.rb
  spec/requests/single_charges/single_charges_spec.rb
  spec/system/single_charges/admin_creates_single_charge_spec.rb
  spec/system/single_charges/admin_views_single_charges_list_spec.rb
Labels: enhancement

#69 Endpoint Taxas de Áreas Comuns
  app/controllers/api/v1/api_controller.rb
  app/controllers/api/v1/common_area_fees_controller.rb
  app/controllers/common_area_fees_controller.rb
  app/models/common_area_fee.rb
  app/views/common_area_fees/new.html.erb
  config/routes.rb
  db/migrate/20240711184518_add_condo_id_to_common_area_fees.rb
  spec/factories/common_area_fees.rb
  spec/models/common_area_fee_spec.rb
  spec/requests/apis/common_area_fee_api_spec.rb
  spec/system/common_areas_fees/admin_sees_common_area_fees_history_spec.rb
  spec/system/common_areas_fees/admin_view_common_area_spec.rb
Labels: API

#77 Fix do endpoint de taxas de áreas comuns
  README.md
  app/controllers/api/v1/common_area_fees_controller.rb
  spec/requests/apis/common_area_fee_api_spec.rb
Labels: bug, API

#84 Cancelamento de taxas condominiais e cobranças avulsas
  app/controllers/base_fees_controller.rb
  app/controllers/single_charges_controller.rb
  app/models/base_fee.rb
  app/models/single_charge.rb
  app/views/base_fees/index.html.erb
  app/views/base_fees/show.html.erb
  app/views/shared_fees/show.html.erb
  app/views/single_charges/index.html.erb
  app/views/single_charges/show.html.erb
  config/locales/base_fees.pt-BR.yml
  config/locales/rails.pt-BR.yml
  config/locales/single_charge.pt-BR.yml
  config/routes.rb
  db/migrate/20240716002312_add_status_to_base_fees.rb
  db/migrate/20240716004427_add_status_to_single_charges.rb
  db/schema.rb
  spec/system/base_fees/admin_cancels_base_fee_spec.rb
  spec/system/shared_fees/admin_cancels_shared_fee_spec.rb
  spec/system/single_charges/admin_cancels_single_charge_spec.rb
Labels: enhancement

#87 Endpoint de Cobranças Avulsas (POST de Multa e Reserva de Área Comum)
  Gemfile.lock
  README.md
  app/controllers/api/v1/single_charges_controller.rb
  config/application.rb
  config/locales/rails.pt-BR.yml
  config/routes.rb
  spec/requests/apis/single_charge_api_spec.rb
Labels: API

#104 Corrige cálculo de fracionamento (shared_fee)
  app/models/shared_fee.rb
  spec/jobs/generate_monthly_bill_job_spec.rb
  spec/models/shared_fee_spec.rb
  spec/system/shared_fees/admin_creates_shared_fee_spec.rb
Labels: enhancement

#103 Endpoint de detalhes de Fatura
  README.md
  app/controllers/api/v1/bills_controller.rb
  app/jobs/generate_monthly_bill_job.rb
  app/models/bill.rb
  app/models/unit.rb
  config/routes.rb
  db/migrate/20240717221617_add_values_fields_to_bill.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/bills.rb
  spec/jobs/generate_monthly_bill_job_spec.rb
  spec/models/bill_spec.rb
  spec/requests/apis/bill_api_spec.rb
Labels: API

#108 Endpoint de Listagem de Faturas pendentes de uma unidade
  README.md
  app/controllers/api/v1/bills_controller.rb
  config/routes.rb
  spec/requests/apis/bill_api_spec.rb
Labels: API

#105 Cobranca Avulsa proprietario
  app/assets/stylesheets/style.scss
  app/controllers/home_controller.rb
  app/controllers/owners/single_charges_controller.rb
  app/controllers/rent_fees_controller.rb
  app/controllers/units_controller.rb
  app/helpers/single_charge_helper.rb
  app/views/home/property_owner_dashboard/_property_owner_dashboard.html.erb
  app/views/home/property_owner_dashboard/_property_owner_profile.html.erb
  app/views/home/property_owner_dashboard/_single_charge.html.erb
  app/views/home/property_owner_dashboard/_unit_section.html.erb
  app/views/owners/single_charges/index.html.erb
  app/views/owners/single_charges/new.html.erb
  app/views/rent_fees/_new_form.html.erb
  app/views/rent_fees/edit.html.erb
  app/views/units/index.html.erb
  config/locales/rent_fee.pt-BR.yml
  config/locales/single_charge.pt-BR.yml
  config/routes.rb
  spec/factories/rent_fees.rb
  spec/models/unit_spec.rb
  spec/requests/property_owners/single_charges/property_owner_creates_single_charge_spec.rb
  spec/support/json/owner_units.json
  spec/system/property_owners/auth/user_tries_to_sign_up_as_property_owners_spec.rb
  spec/system/property_owners/property_owner_views_dashboard_spec.rb
  spec/system/property_owners/rent_fees/property_owner_manages_rent_spec.rb
  spec/system/property_owners/single_charges/property_owner_creates_single_charge_spec.rb
  spec/system/property_owners/single_charges/property_owner_view_single_charge_list_spec.rb
  spec/system/property_owners/units/property_owener_view_unit_details_spec.rb
  spec/system/property_owners/units/property_owner_views_its_units_spec.rb
Labels: enhancement

#90 Atualização do cálculo de fatura
  app/models/base_fee.rb
  app/models/base_fee_calculator.rb
  app/models/bill_calculator.rb
  app/models/unit.rb
  app/views/bills/show.html.erb
  app/views/home/tenant_bill.html.erb
  db/migrate/20240717190806_add_counter_to_base_fees.rb
  db/schema.rb
  spec/factories/base_fees.rb
  spec/factories/shared_fees.rb
  spec/factories/single_charges.rb
  spec/jobs/generate_monthly_bill_job_spec.rb
  spec/models/base_fee_calculator_spec.rb
  spec/models/bill_calculator_spec.rb
  spec/requests/apis/single_charge_api_spec.rb
Labels: enhancement

#106 Endpoint de Recebimento de Comprovante
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/api/v1/receipts_controller.rb
  app/models/receipt.rb
  config/locales/receipts.pt-BR.yml
  config/routes.rb
  db/migrate/20240718020443_create_receipts.rb
  db/schema.rb
  spec/factories/receipts.rb
  spec/models/receipt_spec.rb
  spec/rails_helper.rb
  spec/requests/receipts/receive_a_file_for_receipt_spec.rb
  spec/support/active_storage_validations.rb
  spec/support/images/best_game_ever.webp
  spec/support/images/foto-do-angelo.png
  spec/support/pdf/Comprovante-teste.pdf
Labels: API

#112 Endpoint de cancelamento de reserva de área comum
  README.md
  app/controllers/api/v1/single_charges_controller.rb
  config/locales/single_charge.pt-BR.yml
  config/routes.rb
  db/seeds.rb
  spec/requests/apis/single_charge_api_spec.rb
Labels: API

#114 Garantir que fatura tenha um status
  db/migrate/20240719001429_delete_status_from_bills.rb
  db/migrate/20240719001655_add_status_column_to_bills.rb
  db/schema.rb
  spec/models/bill_spec.rb
Labels: bug, fácil

#110 Atualiza status de fatura
  app/assets/images/check-icon.png
  app/assets/images/comprovante-pg.jpg
  app/assets/images/cupom-fiscal.jpg
  app/controllers/application_controller.rb
  app/controllers/bills_controller.rb
  app/models/bill.rb
  app/models/receipt.rb
  app/views/bills/index.html.erb
  app/views/bills/show.html.erb
  app/views/home/_tenant_dashboard.html.erb
  app/views/home/tenant_bill.html.erb
  config/locales/bills.pt-BR.yml
  config/locales/rails.pt-BR.yml
  config/routes.rb
  db/seeds.rb
  spec/factories/receipts.rb
  spec/models/bill_spec.rb
  spec/models/receipt_spec.rb
  spec/requests/bills/user_tries_to_change_bill_status_spec.rb
  spec/requests/receipts/receive_a_file_for_receipt_spec.rb
  spec/system/bills/admin_changes_bill_status_spec.rb
  spec/system/bills/admin_views_all_bills_of_condo_spec.rb
  spec/system/bills/admin_views_details_of_bill_spec.rb
  spec/system/bills/user_accesses_associated_bill_spec.rb
  spec/system/bills/user_accesses_receipt_spec.rb
Labels: enhancement

#113 Protege rotas de seleção de condomínios
  app/controllers/admins_controller.rb
  app/controllers/application_controller.rb
  app/controllers/common_area_fees_controller.rb
  app/controllers/common_areas_controller.rb
  config/routes.rb
  spec/requests/admins/user_manages_associated_condos_spec.rb
  spec/requests/common_area/admin_access_common_area_details_spec.rb
  spec/requests/common_area/admin_access_common_area_list_spec.rb
  spec/requests/common_area_fee/admin_access_new_common_area_fee_spec.rb
  spec/requests/common_area_fee/update_common_area_fee_spec.rb
  spec/requests/condos/admin_accesses_associated_condos_spec.rb
Labels: enhancement

#120 Protege rotas de BaseFees e Bills
  app/controllers/base_fees_controller.rb
  app/controllers/bills_controller.rb
  app/controllers/common_area_fees_controller.rb
  app/controllers/common_areas_controller.rb
  spec/requests/base_fees/admin_access_base_fee_details_spec.rb
  spec/requests/base_fees/admin_access_index_base_fees_spec.rb
  spec/requests/base_fees/admin_access_new_base_fees_spec.rb
  spec/requests/base_fees/admin_cancels_base_fee_spec.rb
  spec/requests/base_fees/admin_creates_base_fees_spec.rb
  spec/requests/bills/user_access_bills_details_spec.rb
  spec/requests/bills/user_access_bills_list_spec.rb
  spec/requests/bills/user_tries_to_change_bill_status_spec.rb
  spec/requests/common_area_fee/admin_access_new_common_area_fee_spec.rb
Labels: auth

#117 Detalhamento de fatura
  Gemfile.lock
  README.md
  app/assets/images/blurry-receipt.png
  app/controllers/api/v1/bills_controller.rb
  app/controllers/bills_controller.rb
  app/jobs/generate_monthly_bill_job.rb
  app/models/base_fee_calculator.rb
  app/models/bill.rb
  app/models/bill_calculator.rb
  app/models/bill_detail.rb
  app/models/unit.rb
  app/views/bills/_bill_dates.html.erb
  app/views/bills/_bill_description.html.erb
  app/views/bills/_bill_status.html.erb
  app/views/bills/show.html.erb
  config/locales/bills.pt-BR.yml
  db/migrate/20240719122712_add_single_charge_and_rent_fee_to_bills.rb
  db/migrate/20240719123650_create_bill_details.rb
  db/migrate/20240719195651_add_denied_to_bills.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/bill_details.rb
  spec/factories/bills.rb
  spec/models/bill_calculator_spec.rb
  spec/models/bill_detail_spec.rb
  spec/models/bill_spec.rb
  spec/models/unit_spec.rb
  spec/requests/apis/bill_api_spec.rb
  spec/requests/bills/user_access_bills_details_spec.rb
  spec/system/bills/admin_changes_bill_status_spec.rb
  spec/system/bills/admin_views_details_of_bill_spec.rb
Labels: enhancement

#130 Rafatoração de chamadas da API para proprietário
  app/models/property_owner.rb
  app/models/unit.rb
  spec/models/property_owner_spec.rb
  spec/models/unit_spec.rb
Labels: bug, API

#125 Protege rotas de SharedFees e SingleCharges
  app/controllers/shared_fees_controller.rb
  app/controllers/single_charges_controller.rb
  spec/requests/shared_fees/admin_access_new_shared_fee_spec.rb
  spec/requests/shared_fees/admin_access_shared_fee_details_spec.rb
  spec/requests/shared_fees/admin_cancels_shared_fee_spec.rb
  spec/requests/shared_fees/admin_creates_shared_fees_spec.rb
  spec/requests/shared_fees/admin_views_shared_fees_list_spec.rb
  spec/requests/shared_fees/shared_fees_spec.rb
  spec/requests/single_charges/admin_access_new_single_charges_spec.rb
  spec/requests/single_charges/admin_access_single_charges_details_spec.rb
  spec/requests/single_charges/admin_access_single_charges_list_spec.rb
  spec/requests/single_charges/admin_cancels_single_charges_spec.rb
  spec/requests/single_charges/admin_creates_single_charges_spec.rb
  spec/requests/single_charges/single_charges_spec.rb
Labels: auth

#138 Recebe Comprovante de Pagamento com sucesso
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/receipts_controller.rb
  app/models/receipt.rb
  app/models/shared_fee.rb
  db/seeds.rb
  spec/models/receipt_spec.rb
  spec/requests/receipts/receive_a_file_for_receipt_spec.rb
Labels: API

#135 Filtragem de faturas
  app/views/bills/_bills_list.html.erb
  app/views/bills/index.html.erb
  config/locales/bills.pt-BR.yml
  spec/factories/bills.rb
  spec/system/bills/admin_views_all_bills_of_condo_spec.rb
Labels: style
